# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0009_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'introduction_to_models_mti_commoninfo2',
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_students', related_query_name='introduction_to_models_student', to='introduction_to_models.Car'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_teachers', related_query_name='introduction_to_models_teacher', to='introduction_to_models.Car'),
        ),
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('commoninfo2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='introduction_to_models.CommonInfo2')),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'introduction_to_models_mti_student2',
            },
            bases=('introduction_to_models.commoninfo2',),
        ),
        migrations.CreateModel(
            name='Teacher2',
            fields=[
                ('commoninfo2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='introduction_to_models.CommonInfo2')),
                ('cls', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'introduction_to_models_mti_teacher2',
            },
            bases=('introduction_to_models.commoninfo2',),
        ),
    ]
